### ISSUE TITLE
Can't connect to the River Financial LN node

### ISSUE THREAD

**Issue by viaj3ro** [MangoSalad/AtlasWallet#1]
Hi Philip,

unfortunately I couldn't find any other option to contact you so I decided to write you here.

I run the lightning node SilentBob and tried repeatedly to open a channel to the River Financial node:
(03037dc08e9ac63b82581f79b662a4d0ceca8a8ca162b1af3551595b8f2d97b70a@104.196.249.140:9735)

Every time I try, I get back this error:

`peer sent error: ascii='funding failed due to internal error' bin=66756e64696e67206661696c65642064756520746f20696e7465726e616c206572726f72`

Would you be able to investigate the issue or forward me to someone who can? I'm running an eclair v.0.5 node. 

My telegram is @viaj3ro

Thanks and best regards!

**Comment by philipglazman** [comment]
Sorry for late response. Messaged you on Telegram!
